### ISSUE TITLE
[masterbots.ai] Fix: Main Bot Profile Redirection Path Not Reacting

### ISSUE THREAD

**Issue by AndlerRL** [bitcashorg/masterbots#280] opened 2024-10-03 21:20 UTC
The sidebar is no longer reading the path in order to update the `activeBot` post redirection to Chat View.

## DEMO ISSUE:

https://github.com/user-attachments/assets/37269483-eda7-45d2-8db2-c044092c6709

**Comment by AndlerRL** [comment] 2024-10-03 21:22
![](https://github.trello.services/images/mini-trello-icon.png) [[Regression] Route Not Updating Sidebar Navigation](https://trello.com/c/l2IJvuAU/220-regression-route-not-updating-sidebar-navigation)

**Comment by Bran18** [comment] 2024-11-11 15:55
### Update

I'm closing this issue for the following reasons: 

- The issue is fixed. See video.

#### Video


https://github.com/user-attachments/assets/1bee66a5-46b6-4948-a536-0976c7104c4b

**Closed by Bran18** 2024-11-11 15:55 UTC
Labels: bug
